import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: 'zenith-mtn-black',
    slug: 'zenith-mountain-tee-black',
    name: 'Zenith Mountain Tee / Black',
    price: 4500,
    category: 'Drop Shoulder',
    image: '/images/1/1.png',
    images: ['/images/1/1.png', '/images/1/2.png', '/images/1/3.png', '/images/1/4.png'],
    series: 'The Mountain Series',
    description: '450 GSM Heavyweight cotton. Features the architectural "Zenith Mountain" rear graphic and minimalist front identity.',
    fabric: 'Heavyweight cotton jersey',
    fit: 'Drop shoulder',
    gsm: 450,
    stock: 24,
    active: true,
    featured: true,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Vintage Black'],
  },
  {
    id: 'zenith-mtn-white',
    slug: 'zenith-mountain-tee-white',
    name: 'Zenith Mountain Tee / White',
    price: 4500,
    category: 'Regular Fit',
    image: '/images/2/1.png',
    images: ['/images/2/1.png', '/images/2/2.png', '/images/2/3.png', '/images/2/4.png'],
    series: 'The Mountain Series',
    description: 'Optical white heavyweight cotton. Structural drop-shoulder fit with high-density textile printing.',
    fabric: 'Heavyweight cotton jersey',
    fit: 'Regular fit',
    gsm: 450,
    stock: 18,
    active: true,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Pure White'],
  },
  {
    id: 'enso-series-black',
    slug: 'enso-circular-tee-black',
    name: 'Enso Circular Tee / Black',
    price: 4200,
    category: 'Over Sized',
    image: '/images/3/1.png',
    images: ['/images/3/1.png', '/images/3/2.png', '/images/3/3.png', '/images/3/4.png'],
    series: 'The Enso Series',
    description: 'Inspired by the Japanese Enso - a symbol of absolute enlightenment and strength. 300 GSM luxury jersey.',
    fabric: 'Luxury cotton jersey',
    fit: 'Oversized',
    gsm: 300,
    stock: 20,
    active: true,
    featured: true,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Pitch Black'],
  },
  {
    id: 'enso-series-navy',
    slug: 'enso-circular-tee-navy',
    name: 'Enso Circular Tee / Navy',
    price: 4200,
    category: 'Drop Shoulder',
    image: '/images/4/1.png',
    images: ['/images/4/1.png', '/images/4/2.png', '/images/4/3.png', '/images/4/4.png'],
    series: 'The Enso Series',
    description: 'Deep midnight navy palette. Boxy silhouette with articulated Enso brush-stroke graphic.',
    fabric: 'Luxury cotton jersey',
    fit: 'Drop shoulder',
    gsm: 300,
    stock: 16,
    active: true,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Midnight'],
  },
  {
    id: 'earth-signature-tan',
    slug: 'signature-earth-tee',
    name: 'Signature Earth Tee',
    price: 5500,
    category: 'Regular Fit',
    image: '/images/5/1.png',
    images: ['/images/5/1.png', '/images/5/2.png', '/images/5/3.png', '/images/5/4.png'],
    series: 'Earth Collection',
    description: 'Earth-toned luxury. Features the "Zenvor Pattern" mountain logo in marble-textured finish.',
    fabric: 'Premium compact cotton',
    fit: 'Regular fit',
    gsm: 380,
    stock: 12,
    active: true,
    featured: true,
    sizes: ['M', 'L', 'XL'],
    colors: ['Desert Tan'],
  },
];
